name: Deploy to Easypanel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Easypanel deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 5.78.176.115
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker exec easypanel docker service update --force xetux2_inbox
